CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `chat_id` VARCHAR(50) DEFAULT NULL,
  `lang` VARCHAR(10) NULL,
  `step` VARCHAR(50) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `messages` (
  `id` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `chat_id` VARCHAR(50) DEFAULT NULL,
  `message_id` VARCHAR(50) DEFAULT NULL
);